@host = https://localhost:7189

POST {{host}}/api/auth/token/refresh
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY2EwOTg0NGMtNDM4Yi00NDQ2LWFkY2UtYTg0YmQ2OThkM2EyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoic3RhbmRhcmRfdXNlciIsImV4cCI6MTcxMjA3MTY2MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE4OSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcxODkifQ.TfbJBeTCgwnHDoof_B_KO5gayKrYhDDYavhSLlNOi8s",
  "refreshToken": "CwpPqJO8fb5GdcuxhLlwr+CORzBgDENHts86t59Co8o="
}